source ~/.zsh/.aliases.zsh

# initialize starship
eval "$(starship init zsh)"

ff

# initialize completion system
autoload -U compinit ; compinit

setopt AUTO_CD COMPLETE_ALIASES NO_BEEP

# pnpm (autogenerated)
export PNPM_HOME="/home/n/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
