source $ZDOTDIR/.aliases.zsh

# initialize starship
eval "$(starship init zsh)"

ff

# initialize completion system
autoload -U compinit ; compinit

setopt AUTO_CD COMPLETE_ALIASES NO_BEEP

# allow use of control as a modifier key for shortcuts
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^H' backward-kill-word
bindkey '5~' kill-word

# pnpm (autogenerated)
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
